dist: xenial
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    update: true
    packages:
    - openjfx
script: mvn test -Dtestfx.robot=glass -Dglass.platform=Monocle -Dmonocle.platform=Headless -Dprism.order=sw
